name: compile

on:
  push:
    branches:
      - main
    paths:
      - cv.sty
      - cv.tex
      - reference.bib
      - .github/workflows/compile.yml

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          post_compile: |
            mkdir build
            mv cv.pdf ./build

      - uses: actions/upload-artifact@v4
        with:
          name: cv
          path: ./build/cv.pdf

      - name: Push compiled documents to a separate branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: build # The branch the action should deploy to.
          folder: ./build # The folder the action should deploy.
